### ISSUE TITLE
fix uniondht

### ISSUE THREAD

**Issue by Pireo** [imDMG/qBt_SE#1]
Hi imDMG, I wonder if you're capable of fixing a problem this plugin has: relsuts are unclickable.

**Comment by imDMG** [comment]
Hi, Pireo!
Wich one? And what do you mean unclickable?

**Comment by Pireo** [comment]
this plugin: https://raw.githubusercontent.com/nindogo/qbtSearchScripts/master/uniondht.py
EVERY result, if you double click on any of them, nothing happens, while a window with the details ad the download option should open.

**Comment by imDMG** [comment]
Why you wrote me, if plugin has another author?
Anyway, email me, i'll look.

**Comment by Pireo** [comment]
They were aware of the bug but didn't seem capable of fixing it, and you speak russian so, I thought you could be interested.

**Comment by imDMG** [comment]
Yeah, it could be, but, man, you write **issue** for **my** project instead **email**.

**Comment by imDMG** [comment]
Проблема не в плагине, а в том, что qBittorrent пытается перейти по ссылке на загрузку и получает редирект или закрытие соединения (сайт заблокирован, упал). В случае блокировки можно добавить прокси непосредственно в программу (настройки->соединение->прокси-сервер).

**Comment by Pireo** [comment]
I see, sorry for the opened issue.
