### ISSUE TITLE
Плагин nnmclub перестал работать

### ISSUE THREAD

**Issue by ufeemcev** [imDMG/qBt_SE#10]
Пишет "Поиск не дал результатов" при любом запросе.

**Comment by ufeemcev** [comment]
Теперь по неведомой причине всё заработало...

**Comment by ufeemcev** [comment]
В общем наблюдается не стабильная работа, не уверен в чем может быть дело

**Comment by imDMG** [comment]
Проблема связана с недоступностью/задержкой запросов ресурса.
