### ISSUE TITLE
RUTOR plugin doesn't work anymore.

### ISSUE THREAD

**Issue by ElimGarak72** [imDMG/qBt_SE#11]
Hello.

It has been a couple of days now that every search returns this error:
[Error]: http://rutor.info/ is not response! Maybe it is blocked.

Thank you and have a nice day.

**Comment by imDMG** [comment]
Hi!

Yes confirm. I'll see.

**Comment by imDMG** [comment]
It strange, but Rutor refuses some proxies, even my own, but some works.

**Comment by ElimGarak72** [comment]
I have tried setting my VPN in Belorus and it works, so it may have something to do with the current situation.

**Comment by imDMG** [comment]
I think its temp problems on Rutor side. Will see.

**Comment by imDMG** [comment]
![изображение](https://user-images.githubusercontent.com/1889770/157495645-a0e1cc44-5120-4b58-9cc2-9420f81a45db.png)
This is a random proxy that I could find on the Internet.
So, I advise you to find a working proxy or VPN.

**Comment by ElimGarak72** [comment]
Thank you for your help.
Unfortunately, no proxy seems to work for me (even the one you posted).
I may use the VPN, but there is the other issue that rutor only works alone.
I guess I will just have to stop using it for a while.
Thanks anyway!
