### ISSUE TITLE
Proxy list

### ISSUE THREAD

**Issue by Stebalso** [imDMG/qBt_SE#12]
Есть ли возможность добавить ссылку на внешний файл в txt (http-list-proxy.txt , https-list-proxy.txt  из которых будет перебор прокси ?

**Comment by imDMG** [comment]
Можно сделать так:
заменить
```python
    with open(PROXY_FILE) as f:
        proxy_list = [x.rstrip() for x in f]
```
на
```python
    if PROXY_FILE.startswith("http"):
        opener = build_opener()
        with opener.open(PROXY_FILE) as r:
            proxy_list = [x.rstrip().decode("utf-8") for x in r]
    else:
        with open(PROXY_FILE) as f:
            proxy_list = [x.rstrip() for x in f]
```

**Comment by Stebalso** [comment]
Моя благодарность, отпиши в личку , кину донат на donut

**Comment by Foxtrod89** [comment]
Can you add SOCKS5 proxy so I can use **nordvpn**'s proxy list.

**Comment by imDMG** [comment]
You cna try this notation:
`"socks5://<userid>@proxy-host"`
