### ISSUE TITLE
Плагин для rutracker в списке неофициальных плагинов

### ISSUE THREAD

**Issue by qarkai** [imDMG/qBt_SE#13]
Добавь, пожалуйста, ссылку на плагин в https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins.
Возникает путаница навроде https://github.com/nbusseneau/qBittorrent-RuTracker-plugin/issues/42#issuecomment-1066546644
И немного странно, что остальные три плагина есть в списке, а rutracker.py нет.

**Comment by imDMG** [comment]
Хм, ок, добавлю.
Не добавлял лишь потому, что тот был/есть рабочий.
