### ISSUE TITLE
Плагин rutracker замедляет запуск приложения

### ISSUE THREAD

**Issue by qarkai** [imDMG/qBt_SE#15]
Без плагина окно приложения появляется практически мгновенно.
С плагином секунд через десять после запуска.
Отключение в списке плагинов не влияет на задержку.
Остальные плагины не влияют на время запуска.

**Comment by imDMG** [comment]
Хм, не могу у себя подтвердить. Запускается почти мгновенно как с плагином, так и без него.

**Comment by imDMG** [comment]
Какая ОС и версия qBt?

**Comment by qarkai** [comment]
Arch Linux, v4.4.1.

**Comment by imDMG** [comment]
В конце rutracker.py удалите или закомментируйте:
```python
    if BASEDIR.parent.joinpath("settings_gui.py").exists():
        from settings_gui import EngineSettingsGUI

        EngineSettingsGUI(FILENAME)
```
сохраните и перезапустите приложение.

**Comment by qarkai** [comment]
Непонятно что это даёт. `settings_gui.py` в `~/.local/share/qBittorrent/nova3` не было.
Тем не менее сделал, не помогло.

**Comment by imDMG** [comment]
Я помню что были какие-то проблемы с модулем `tkinter` на какой то определенной версии линукса...
Возможно дело в прокси? Такое ощущение, что скрипт ждет ответа от сервера (5с. + 5с, повторной попытки)

**Comment by imDMG** [comment]
Я не уверен, что именно делает qBt на старте с плагинами, проверяет ли их на соответствие или тестирует. Если второе, то он у каждого плагина запускает метод `search`.
Очень странно. Сам плагин работает нормально, без задержек?

**Comment by qarkai** [comment]
Сам плагин возвращает 403. Рутрекер сейчас защищается CloudFlare.

**Comment by qarkai** [comment]
Кстати, с включенным VPN для обхода блокировок РКН задержка не такая большая, но всё равно заметная: ~3-5 секунд.

**Comment by imDMG** [comment]
Видимо qBt все таки тестирует плагины на старте. Если это так, то почему у вас вешается приложение, а у меня нет, даже если я отключаю прокси.

**Comment by imDMG** [comment]
Возможно это особенности версии 4.4.1 (у меня 4.3.9) или сборки под вашу ОС? Попробуйте проследить какие TCP запросы делает `python` на старте приложения (у меня никаких).

**Comment by qarkai** [comment]
Дело в cookies. В `__init__` загружается `rutracker.cookies`. У меня его нет, т.к. плагин не может залогиниться и сохранить cookies из-за 403. Поэтому вызывается `self.login()`.
Можете добавить зеркала rutracker? На rutracker.net вроде бы нет защиты.

**Comment by imDMG** [comment]
Надо было сначала попросить вас запустить скрипт в терминиле, но хорошо, что разобрались =)
В целом могу добавить зеркала, но проблема в том, что это не гарантирует, что на этом зеркале не включат защиту. Я могу, конечно, перебором проверять доступность (ловить ошибки 403, 503 и т.д.), но это сильно увеличит задержку плагина.

**Comment by qarkai** [comment]
Ок. В общем, мне помогло вот такое:
```diff
        except FileNotFoundError:
-            self.login()
+            pass
```

**Comment by imDMG** [comment]
Ок, на время пойдет. Только не забудьте поменять, когда трекер будет доступен ;)

**Comment by qarkai** [comment]
А надо? Как я понимаю, логин произойдёт при первом поиске по условию `if "log-out-icon" not in page`.

**Comment by imDMG** [comment]
А, точно, я эту проверку недавно добавил.

чт, 24 мар. 2022 г., 00:51 Arkadiy Illarionov ***@***.***>:

**Comment by imDMG** [comment]
Потестировал вариант с зеркалами и выяснил, что если cookies загружены и валидны, то пускает на `.org` и `.nl`, а `.net` возвращает не html страницу (скорее всего капча).
