### ISSUE TITLE
Путь к скриптам на GNU/Linux

### ISSUE THREAD

**Issue by vladiscripts** [imDMG/qBt_SE#19]
Ошибка в справке README.md. Из-за которой потерял не один час времени, и делал много переустановок.
На Linux скрипты устанавливаются по пути: ~/.local/share/**data**/qBittorrent/nova3/engines/
https://github.com/qbittorrent/qBittorrent/wiki/Frequently-Asked-Questions#Where_does_qBittorrent_save_its_settings

**Comment by imDMG** [comment]
Спасибо!

**Comment by imDMG** [comment]
Да, у меня было изначально так, но мне прилетел [пул](https://github.com/imDMG/qBt_SE/pull/14) и я его закомитил не глядя.
