### ISSUE TITLE
[Error] We not authorized. Please check your credentials.

### ISSUE THREAD

**Issue by ShivaSingh361** [imDMG/qBt_SE#22]
My credentials are correct. But, It still shows me this error. Kindly help.

**Comment by ShivaSingh361** [comment]
nevermind. It worked when I relogged in Rutracker.

**Comment by Shellyoung** [comment]
It worked for me after I repeated ShivaSingh361's advice 3-10 times. Strange.

**Comment by Foxtrod89** [comment]
same here

**Comment by imDMG** [comment]
In this case you can use any vpn on you pc and turn off proxy in plugi-in.

**Comment by zorhay** [comment]
> It worked when I relogged in Rutracker! If anyone facing this issue. You have to relog in Rutracker from your browser.

When I logged in again, Rutracker asked for a captcha. The issue may be there.

**Comment by sadtango289** [comment]
How to fix it ? Im a low-tech. Please make it simple. 

![image](https://github.com/user-attachments/assets/3d98837b-c978-400d-a91a-63de95edea83)

**Comment by imDMG** [comment]
You need to enter login/password from site in associated `*.json` file.
