### ISSUE TITLE
Скачивание

### ISSUE THREAD

**Issue by w202mg** [imDMG/qBt_SE#23]
Добрый день,
после выполения поиска и нажатия на "скачать" скачивание не начинается. Логин и пароль сохранены и работают (не появляется ошибка). Можно, кончено и вручную, но тогда и смысл плагина теряется. Еще активировал в конфиге магнитные ссылки- не помогло.

Подскажите, пожалуйста, как решить.

Благодарю.

**Comment by imDMG** [comment]
Привет.
Вы не указали какой именно плагин.

**Comment by w202mg** [comment]
> Привет. Вы не указали какой именно плагин.

Извиняюсь. Rutracker.

**Comment by imDMG** [comment]
Хм, странно, у меня все работает. Попробуйте двойной клик.

**Comment by w202mg** [comment]
>  // Странное поведение возможно из-за прокси/впн.

Прокси отключен

**Comment by w202mg** [comment]
В диалоге "Скачать" ссылка отображается корректно. По ссылке торренто файл скачивается

**Comment by imDMG** [comment]
Вы используете программу или веб-интерфейс? ОС?

**Comment by w202mg** [comment]
> Вы используете программу или веб-интерфейс? ОС?

веб-интерфейс. qbittorrent запущен на Дебиан 11.

**Comment by imDMG** [comment]
Так, попробовал сделать по вашему алгоритму. Через веб-интерфейс рутрекер возвращает ошибку 
![изображение](https://user-images.githubusercontent.com/1889770/195157348-a14ab111-be0d-4879-ad58-2b94a6c96d12.png)
Как я понял, при такой схеме плагин не участвует в скачивании, т.е. он передает эту функцию самой программе либо веб-клиенту.
В моем случае, если я попытаюсь открыть [ссылку](http://rutor.info/torrent/325218/doktor-kto-den-doktora_doctor-who-the-day-of-the-doctor-2013-bdrip-1080p-ot-ash61-3d-video-halfou-p) без впн/прокси у меня ничего не получится, но [поддомен](http://d.rutor.info/download/325218) не заблокирован, поэтому из веб-интерфейса торрент добавляется.
Попробуйте поставить впн на сервер или клиент.

**Comment by w202mg** [comment]
попробовал подключить VPN, без изменений. при ручном добавлении иагнитной ссылки качает нормально.

**Comment by imDMG** [comment]
С магнитной ссылкой будет работать, да, но чтобы ее получить, при создании списка торрентов, нужно делать по одному дополнительному запросу на торрент, ибо она находится внутри торрента на сайте. Опять же, да, у рутрекера есть свое АПИ (слебенькое) через которое мы можем получить магнет-ссылку, но там есть ограничение, емнип 100 на IP.

> попробовал подключить VPN, без изменений. подключал на сервере. при ручном добавлении магнитной ссылки качает нормально.

На клиенте пробовали?

**Comment by imDMG** [comment]
Попробуйте [альтернативный](https://raw.githubusercontent.com/nbusseneau/qBittorrent-rutracker-plugin/master/rutracker.py) плагин.

**Comment by w202mg** [comment]
интересно, что если я создаю текстовый файл со скриптом, то программа не открывает файл. подгружает плагин только из интернета с моего удаленного сервера, но теперь еще стал ругаться и на логин/пароль, хоть они остались прежние. на трекере не требует капчу и заходит нормально. другой плагин даже через интернет не загружвется.

**Comment by w202mg** [comment]
переустоновил qBittorrent, тоже самое

**Comment by imDMG** [comment]
На сервере программа ничего не сообщает?

**Comment by w202mg** [comment]
> На сервере программа ничего не сообщает?

нет

**Comment by imDMG** [comment]
Скорее всего ничего не поможет, кроме магнет-ссылок. Потому что ссылка на загрузку передается напрямую программе, минуя плагин, а она не учитывает куки для авторизации. Файлы будут скачиваться только с открытых от регистрации торрентов.

**Comment by w202mg** [comment]
Импортирую как файл, ругается, что плагин не поддерживается. Версия клиента 4.2.5

![image](https://user-images.githubusercontent.com/84856053/195421516-f0b17e4f-b488-4ea5-96dc-b12877e86851.png)

**Comment by w202mg** [comment]
на 4.4.5 тоже самое

**Comment by w202mg** [comment]
в скрипте ничего не меняю, только втсавляю свой логин и пароль, и то и то без каких-либо специальных знаков

**Comment by imDMG** [comment]
Название, строго, должно быть rutracker.py.

**Comment by w202mg** [comment]
> Название, строго, должно быть rutracker.py.

Плагин встал, но без изменений. Попробовал обе версии клиента- 4.2.5 установленный через пакетный менеджер и 4.4.5 в виде Appimage. Магнитные ссылки ловит только установленная версия, в веб-интерфейсе по прежнему обе версии не начинают скачки ни по двойному клику ни серез меню правой кнопки мыши.

**Comment by imDMG** [comment]
В веб-интерфейсе при загрузке, появляется окно? Если да, какая ссылка внутри?

**Comment by imDMG** [comment]
Вы точно переключили в конфиге настроку magnet в true?
