### ISSUE TITLE
"kinozal.tv blocked" as search results

### ISSUE THREAD

**Issue by ElimGarak72** [imDMG/qBt_SE#24]
Hello.

It has been a few days now that every search returns a "[<search key>][Error]: http://kinozal.tv/browse.php?s=<search key>&c=0 is blocked. Try another proxy." with a 1,000tb dimension of the file and 100 peers and seeds.

Thank you.

**Comment by imDMG** [comment]
Hi.
You right. They, finally, turned to https.
I've update kinozal.py to 2.10 version. Don't forget change proxy to https, if you used it.
