### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by MMMXXXZZZ** [imDMG/qBt_SE#28]
Getting error "Couldn't install "rutor/nnmclub" search engine plugin. Plugin is not supported".

Latest qBittorrent version.

**Comment by imDMG** [comment]
You can put file *.py directly in plugins folder:
* Windows: %localappdata%\qBittorrent\nova3\engines
* Linux: ~/.local/share/data/qBittorrent/nova3/engines
* OS X: ~/Library/Application Support/qBittorrent/nova3/engines

**Comment by aptac01** [comment]
> You can put file *.py directly in plugins folder:

А толку то? положил несколько плагинов вот сюда

C:\Users\my_user\AppData\Local\qBittorrent\nova3\engines

и никакого эффекта, перезапускал, переустанавливал - без толку

**Comment by imDMG** [comment]
Возможно вам нужно указать прокси в конфиге плагина.

**Comment by imDMG** [comment]
Так, словил проблему, что никакой плагин не отображается и нельзя установить новый. Пофиксил полностью удалив содежримое **\engines**, заранее скопировав в другое место. После поочередно установил все из бэкапа.

**Comment by JJRousseau** [comment]
RuTracker has the same issue. Manually adding the files does not work. I'm using 4.5.3

**Comment by imDMG** [comment]
Try to use proxy.
