### ISSUE TITLE
Proxy with auth

### ISSUE THREAD

**Issue by fewdji** [imDMG/qBt_SE#29]
Does it suport proxies with auth?
I'm setting in format:
    "http": "user:password@ip:port"
but got error: "Proxy is bad!"

**Comment by imDMG** [comment]
Right now no, but you can add it yourself.
After `build_opener, ProxyHandler` add `, HTTPBasicAuthHandler` and bellow `self.session.add_handler(ProxyHandler(config.proxies))` add `self.session.add_handler(HTTPBasicAuthHandler())` (Following the indentation)
