### ISSUE TITLE
expected value (list, dict, int or string) in bencoded string

### ISSUE THREAD

**Issue by rbasa349** [imDMG/qBt_SE#31]
**rutracker** and **kinozal** doesn't download torrent file (search works fine), magnet-link (kinozal) have same problem

log says `expected value (list, dict, int or string) in bencoded string`

nnm-club and rutor have no problem

**Comment by imDMG** [comment]
I think problem in torrent file https://github.com/qbittorrent/qBittorrent/issues/10696

**Comment by rbasa349** [comment]
> I think problem in torrent file [qbittorrent/qBittorrent#10696](https://github.com/qbittorrent/qBittorrent/issues/10696)

i test again and all works fine via app, and doesn't work via web-UI. it's qb problem
