### ISSUE TITLE
hdrezka

### ISSUE THREAD

**Issue by joey00797** [imDMG/qBt_SE#33]
Приветствую страннник)
не мог бы ты сделать плагин для hdrezk^и
очень хороший трекер)

**Comment by imDMG** [comment]
Привет.
Можно глянуть официальный сайт?

**Comment by joey00797** [comment]
да, канешно
https://rezka.cc/

**Comment by imDMG** [comment]
У треккера не большая посещаемость и мало новинок.

**Comment by joey00797** [comment]
правильно, потому что все смотрят в онлайне. 
а по новинкам, они сначала в кинотеатре, а потом добаляют на трекер
