### ISSUE TITLE
Поддержка SOCKS прокси

### ISSUE THREAD

**Issue by rnqlover** [imDMG/qBt_SE#34]
Доброго времени суток.
Поддерживается ли SOCKS5 прокси? Попробовал разными способами вбить в .json, но безуспешно.

**Comment by imDMG** [comment]
Привет.
К сожалению, на данный момент, не поддерживается.

**Comment by rnqlover** [comment]
Спасибо

**Comment by Xoma163** [comment]
> Привет. К сожалению, на данный момент, не поддерживается.

А планируется?

**Comment by imDMG** [comment]
Проблема в том, что в питоне нет поддержки SOCKS5 "из коробки". Рядом с плагинами поиска (qBittorrent/nova3) есть модуль `socks.py`, но он значительно устарел. Я могу его исправить, но в любом случае, это усложнит установку и использование. Если кому-то сильно нужно, могу написать инструкцию.

**Comment by Xoma163** [comment]
> Проблема в том, что в питоне нет поддержки SOCKS5 "из коробки". Рядом с плагинами поиска (qBittorrent/nova3) есть модуль `socks.py`, но он значительно устарел. Я могу его исправить, но в любом случае, это усложнит установку и использование. Если кому-то сильно нужно, могу написать инструкцию.

Сам торрент использует у меня сокс5 прокси. Хз откуда он берёт его поддержку, но работает.
Просто обидно, что у меня данный плагин не взлетает с http(s) проксями по непонятным мне причинам. DNS вроде гугловские, но ошибка 
[Error]: https://rutracker.org/forum/tracker.php?nm=doctor&c=-1 is not response! Maybe it is blocked.

Мб вы знаете в чём может быть дело или как обойти? Хочется искать торренты в qbittorrent не переходя более никуда

**Comment by imDMG** [comment]
> Мб вы знаете в чём может быть дело или как обойти? Хочется искать торренты в qbittorrent не переходя более никуда
Скорее всего из-за **cloudflare**, возможно ваш прокси не проходит проверку.

**Comment by imDMG** [comment]
С версии qbittorrent 5.1 появилась поддержка socks5. Обновите программу и плагины.
