### ISSUE TITLE
Starting qbittorrent deletes credentials in .json file

### ISSUE THREAD

**Issue by Master-Of-Shadows** [imDMG/qBt_SE#35]
So I enter credentials in the .json file, save, close, turn on qbittorrent, try to search and I get not authorized. Checking .json I see it was overridden back to default. 

Trying to use gui in the parent nova3 folder but I can't enter anything. Fields are blocked. 
https://i.imgur.com/oAodaxH.jpeg

**Comment by imDMG** [comment]
Maybe `json` corrupt. Reinstall plugin.
