### ISSUE TITLE
Rutracker plugin not working anymore

### ISSUE THREAD

**Issue by fabiorfreitas** [imDMG/qBt_SE#4]
I had it working as expected for some time, but now I don't get any results from Rutracker no matter what. I verified that I have the most recent version, that I have my credentials set correctly, that I can access Rutracker normally by other means, that these searches had results there and that I wasn't filtering results out and also tried redoing the login on browser. 

Even after all that, it still doesn't work. My Execution Log has nothing to show, sadly.

**Comment by imDMG** [comment]
Yes, you right. I'll see what the problem is.

**Comment by imDMG** [comment]
Fix it.

**Comment by fabiorfreitas** [comment]
I can confirm that it's working perfectly again, thank you!

Also, I'd like to point out that updating by "check for updates" on qbittorrent didn't work, I had to manually download from GitHub. Other than that, it's perfect.

**Comment by imDMG** [comment]
"Check for updates" works only with plugins written by authors qbittorrent, because inside the code of any plugins hasnt link for update.

**Comment by fabiorfreitas** [comment]
Hm, I understand. Thank you!
