### ISSUE TITLE
домен kinozal.tv в России заблокирован

### ISSUE THREAD

**Issue by almirus** [imDMG/qBt_SE#5]
Заменил в плагине на работающий домен https://kinozal-tv.appspot.com/
задал в kinozal.json правильный логин пароль, но плагин ничего не находит, ошибок тоже нет

**Comment by imDMG** [comment]
Ок, наконец и я с этим столкнулся.
Все потому, что страница с этого зеркала сжата методом gzip и ее нужно распаковывать.
Я могу дать хотфикс. К следующей версии я напишу более универсальное решение.
Итак, в **kinozal.py** заменить 230 строку на
`page = gzip.decompress(response.read()).decode('cp1251')`
и на 6 стоке, после
`import base64`
добавить
`import gzip`

**Comment by almirus** [comment]
работает, спасибо

**Comment by imDMG** [comment]
Работает, да не совсем. Из-за того, что в этом зеркале немного измены ссылки, парсер выдает некорректные ссылки на загрузку. Фикс:
266 строка, заменить на
`"link": f"{self.url_dl}download.php?id={tor[0].split('=')[-1]}",`

PS из-за того, что сайты-зеркала не всегда идентичны оригиналам, я, в который раз, откладываю добавление функционала алиасов (aliases).
