### ISSUE TITLE
nnmclub скачивает торрент с другими анонсерами

### ISSUE THREAD

**Issue by AlexMak58** [imDMG/qBt_SE#6]
Плагин почему-то скачивает торрент с нерабочими анонсерами, а с сайта я скачиваю торрент  с рабочими анонсерами. Хэш-сумма одинакова. В чем причина такого поведения?
В сообщении трекера получаю `unregistered torrent pass`.

**Comment by imDMG** [comment]
Хм, очень странно. Используете прокси или прямое соединение?

**Comment by AlexMak58** [comment]
> Хм, очень странно. Используете прокси или прямое соединение?

Использую [ReQrypt](https://github.com/basil00/reqrypt) (1.4.1, Windows 10 x64) для всей системы.

**Comment by imDMG** [comment]
Попробуйте рандомный прокси при отключенном ReQrypt, чтобы понять на каком уровне это происходит.

**Comment by AlexMak58** [comment]
Удивительно, но плагин резко перестал поддерживаться.
![image](https://user-images.githubusercontent.com/34411074/82229925-b35fc000-9933-11ea-9ef0-8ffad5bee942.png)

<details>
<summary>Версия qBittorrent</summary>

![image](https://user-images.githubusercontent.com/34411074/82230011-d5594280-9933-11ea-957f-913a15ca72cf.png)

</details>

**Comment by imDMG** [comment]
Так происходит, скорее всего, если qBittorrent не удалось получить ответ/данные от сервера, т.е. прокси для трекера не рабочий.

**Comment by AlexMak58** [comment]
Проксирование через Tor Browser (127.0.0.1:9150) почему-то тоже не работает.

**Comment by imDMG** [comment]
Я несколько дней назад напсал скрипт для проверки прокси из списка из файла proxylist.txt: [proxychecker.py](https://github.com/imDMG/qBt_SE/blob/master/proxychecker.py)

**Comment by AlexMak58** [comment]
Воспользовался Вашим скриптом и рабочими прокси из вывода, но все равно получаю `[.][Error]: https://nnmclub.to/forum/ is not response! Maybe it is blocked.`

**Comment by AlexMak58** [comment]
Удалось запустить поиск с помощью [GoodbyeDPI](https://github.com/ValdikSS/GoodbyeDPI). Проблема действительно не в Вашем скрипте. Скачал один и тот же торрент-файл с помощью скрипта и браузера — новые трекеры не добавились, значит торрент-файлы полностью идентичны.

**Comment by imDMG** [comment]
Вот и славно :)

**Comment by AlexMak58** [comment]
Заметил, что через какое-то время все повторяется: возможно, каким-то образом «портится» cookie-файл и анонсеры снова становятся «битые». Решается путем удаления файла `nnmclub.cookie`.

**Comment by imDMG** [comment]
Интересно, может быть они добавили механизм изменения куки при загрузки файла или авторизации. Я понаблюдаю.

**Comment by imDMG** [comment]
Можете выложить 2 файла одного торрента (рабочий и не рабочий)?

**Comment by AlexMak58** [comment]
[Торренты.zip](https://github.com/imDMG/qBt_SE/files/4708056/default.zip)

**Comment by imDMG** [comment]
В целом да, файлы различаются только тем, что в них разные анонсеры. Но. Дело в том, что у меня по этим файлам все одинаково скачивается. Более того, я сам попробовал скачать этот торрент через сайт и через плагин и у меня тоже разница в анонсерах, но торренты загружаются одинаково.
У вас не работают все анонсеры и вы не можете загружать файлы? Или же у вас работает один, а остальные нет, как у меня, и вас это беспокоит?

![изображение](https://user-images.githubusercontent.com/1889770/83359129-b1651a80-a391-11ea-9f63-32817b80bb58.png)

**Comment by AlexMak58** [comment]
Дело не в том, что анонсеры в торрент-файлах не работают и я не могу скачать файлы, а в том, что если скачивается «правильный» торрент-файл с «правильными» анонсерами, то я могу отследить это в профиле NoNameClub (см. скрин) и это будет считаться в мою статистику. Скачать файлы можно и вообще без анонсеров.
![image](https://user-images.githubusercontent.com/34411074/83359750-e9b22c00-a384-11ea-82e4-3e7c94185801.png)
![image](https://user-images.githubusercontent.com/34411074/83359754-ef0f7680-a384-11ea-965a-0b35c7b3d448.png)
А если скачивать «неправильный» торрент-файл с «неправильными» анонсерами, то это, соответственно, не будет учитываться в статистику, так как, возможно, плагин скачивает торрент-файл с другим PassKey-ключом.
![image](https://user-images.githubusercontent.com/34411074/83359417-cc7c5e00-a382-11ea-9a1c-5ff9f07d3891.png)
![image](https://user-images.githubusercontent.com/34411074/83359745-e3bc4b00-a384-11ea-9420-34b9117cca70.png)

**Comment by imDMG** [comment]
Ок, теперь я понял цель. В статистике на сайте, действительно, не отображается загрузка/раздача. Попробую разобраться.

**Comment by imDMG** [comment]
Скорее всего это из-за сессионного ключа **phpbb2mysql_4_sid**, поскольку при загрузке `https://nnmclub.to/forum/download.php?id=fileid` происходит редирект на `https://nnm-club.ws/download.php?csid=sessionid&uid=userid&id=fileid`, где **sessionid** это ключ нашей сессии.
Вы правильно заметили, что при удалении куки-файла все работает нормально, но если к сайту долго не обращаться, то сессия на сервере удаляется.
Видимо придется раз в сутки перезаписывать куки-файл.

**Comment by AlexMak58** [comment]
Хм, значит это нужно как-то автоматизировать, либо обратиться к администраторам торрент-трекера (но маловероятно, что они будут что-то менять).

**Comment by imDMG** [comment]
Обновил плагин. Теперь при каждом запросе будет проверятся зашел ли пользователь, если нет то делаем вход.
Тут все так сложилось, что сам nnm никак не ограничивает гостей (искать, скачивать) поэтому я и не замечал, что долгое время был гостем. Плюс очень короткая сессия, в рутрекера аж 10 лет.

**Comment by AlexMak58** [comment]
Хорошо, будем пробовать.
