### ISSUE TITLE
nnm-club плагин не поддерживается

### ISSUE THREAD

**Issue by saprys** [imDMG/qBt_SE#7]
Плагин nnm не работает, при установке написано плагин не поддерживается. соединение прямое.

**Comment by imDMG** [comment]
Обновление или свежая установка?

**Comment by saprys** [comment]
Свежая

**Comment by imDMG** [comment]
Обновите плагин до 2.6, исправил один недочет.

**Comment by saprys** [comment]
Спасибо, работает.
