### ISSUE TITLE
"[Error]: http://rutor.info/ is not response! Maybe it is blocked"

### ISSUE THREAD

**Issue by Korb** [imDMG/qBt_SE#8]
When trying to search using the search engine [Rutor 1.2 (30/Mar/2021)](https://raw.githubusercontent.com/imDMG/qBt_SE/master/rutor.py) in qBittorrent v4.3.9, the following error appears:

> [Error]: http://rutor.info/ is not response! Maybe it is blocked.
> Size: 1,000 TIB
> Seeders: 100
> Leechers: 100
> Search engine: http://rutor.info/

Login and password are included in the text of the rutor.py before adding it to the qBittorrent. When trying to open the site http://rutor.info in the Mozilla Firefox 95.0b6 (64-bit), an error appears:

> Secure Site Not Available
> A HTTPS version of rutor.info is not available.
> What could be causing this?
> * Most likely, the web site simply does not support HTTPS.
> * It’s also possible that an attacker is involved. If you decide to visit the web site, you should not enter any sensitive information like passwords, emails, or credit card details.

**Comment by imDMG** [comment]
Probably you using incorect proxy or not using at all.

**Comment by Korb** [comment]
@imDMG, i don't use proxy:
_
![2021-11-14_22-18-26](https://user-images.githubusercontent.com/3509797/141695367-8fbf681e-2edb-4f8b-9dfc-e763c1e20c56.png)
![2021-11-14_22-21-52](https://user-images.githubusercontent.com/3509797/141695368-e6a3850c-be8c-41fe-82da-c2df80b55a79.png)

**Comment by imDMG** [comment]
Your provider isnt blicking those torrents?

**Comment by Korb** [comment]
How can I check this?

When I download a .torrent file from rutor.info and open it in qBittorrent, the distribution files are downloaded correctly.

**Comment by imDMG** [comment]
Open in clear browser, like IE or somthing else, that you not use.

**Comment by Korb** [comment]
Microsoft Edge 95.0.1020.53 x64:

> Приносим извинения, но просмотр этой страницы запрещен на территории Российской Федерации в соответствии с постановлением Правительства Российской Федерации от 26 октября 2012 года № 1101 "О единой автоматизированной информационной системе «Единый реестр доменных имён, указателей страниц сайтов в информационно-телекоммуникационной сети „Интернет“ и сетевых адресов, позволяющих идентифицировать сайты в информационно-телекоммуникационной сети „Интернет“, содержащие информацию, распространение которой в Российской Федерации запрещено"

Does this mean that in order to use this search engine in the qBittorrent settings, I need to specify a working proxy? Or use a VPN.

**Comment by imDMG** [comment]
Yes, or you can setup proxy rigth in plugin settings .json file.

**Comment by Foxtrod89** [comment]
I was getting same result recently. ISP wasn't involved in transaction. Basic troubleshooting didn't do a justice either...
